import builtinDefs, { builtIns, defineBuiltin, navClickBuiltin, navClickDef } from "./builtins/defs/index.js";
import {
    NAV_CLICK_SELECTOR,
    applyMarkup,
    currentDocument,
    currentLocationHref,
    currentLocationOrigin,
    extractSourceMarkup,
    extractSourceNode,
    fetchHtml,
    hydrateScripts,
    isPlainClick,
    isSameDocumentFragment,
    parseHtmlDocument,
    readAttr,
    readBool,
    readFallbackValue,
    resolveCurrentUrl,
    resolveDestinationInput,
    resolveElement,
    resolveHref,
    resolveNode,
    resolveSourceInput,
    resolveSpaType,
    resolveUrl,
} from "./builtins/defs/navClick.js";

export {
    NAV_CLICK_SELECTOR,
    applyMarkup,
    builtIns,
    builtinDefs,
    currentDocument,
    currentLocationHref,
    currentLocationOrigin,
    defineBuiltin,
    extractSourceMarkup,
    extractSourceNode,
    fetchHtml,
    hydrateScripts,
    isPlainClick,
    isSameDocumentFragment,
    navClickBuiltin,
    navClickDef,
    parseHtmlDocument,
    readAttr,
    readBool,
    readFallbackValue,
    resolveCurrentUrl,
    resolveDestinationInput,
    resolveElement,
    resolveHref,
    resolveNode,
    resolveSourceInput,
    resolveSpaType,
    resolveUrl,
};

export default builtinDefs;
